import Head from "next/head";
import PersonAddAltOutlinedIcon from "@mui/icons-material/PersonAddAltOutlined";
import Form from "../components/Form";

export default function Home() {
  return (
    <section>
      <Head>
        <title>CRUD App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-5 px-10 md:px-20">
        <h1 className="text-xl font-bold md:text-4xl text-center py-5">
          Employee Management
        </h1>
        <div className="container py-4 mx-auto border-b">
          <button className="py-2 px-4 rounded-sm text-white bg-blue-500 flex items-center gap-1 hover:text-gray-300">
            <span>Add Employee</span>
            <span>
              {" "}
              <PersonAddAltOutlinedIcon />{" "}
            </span>
          </button>
        </div>

        {/* form section */}
        <div className="py-5">
          <Form />
        </div>
      </main>
    </section>
  );
}
