import Head from "next/head";
import PersonAddAltOutlinedIcon from "@mui/icons-material/PersonAddAltOutlined";
import Form from "../components/Form";
import Table from "../components/Table";
import { useDispatch, useSelector } from "react-redux";
import { toggleChangeAction } from "../redux/reducer";

export default function Home() {
  const visible = useSelector((state) => state.app.client.toggleForm);
  const dispatch = useDispatch();
  const handleClick = () => {
    dispatch(toggleChangeAction());
  };
  return (
    <section>
      <Head>
        <title>CRUD App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-5 px-10 md:px-20">
        <h1 className="text-xl font-bold md:text-4xl text-center py-5">
          Employee Management
        </h1>
        <div className="container py-4 mx-auto border-b flex justify-center lg:justify-start">
          <button
            onClick={handleClick}
            className="py-2 px-4 rounded-sm text-white bg-blue-500 flex items-center gap-1 hover:text-gray-300"
          >
            Add Employee
            <span>
              {" "}
              <PersonAddAltOutlinedIcon />{" "}
            </span>
          </button>
        </div>

        {/* form section */}
        {visible ? <Form /> : <></>}

        <div className="py-5">
          <Table />
        </div>
      </main>
    </section>
  );
}
